### ISSUE TITLE
`objs_servald': No such file or directory

### ISSUE THREAD

**Issue by JulianNaumann** [umr-studenten/serval-management#5]
After configuring with `ServalHelper -a wifi`and fixing the configuration using `autoreconf -f -i -I m4` [(see issue #4)](https://github.com/umr-ds/serval-management/issues/4), `make` reports an error:

```
#### Running "make servald" ####
find: `objs_servald': No such file or directory
```

It finished making nonetheless.

run on Raspbian GNU/Linux 8 (jessie)

**Comment by adur1990** [comment]
This is not a bug, but a warning from the servald makefile. Can't fix it here.
